/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import koneksi.koneksi;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ACER
 */
public class menu extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mbrg = new javax.swing.JMenuItem();
        mksr = new javax.swing.JMenuItem();
        mplgn = new javax.swing.JMenuItem();
        mnota = new javax.swing.JMenu();
        nota = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        lapPeng = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu2.setText("Master");

        mbrg.setText("Barang");
        mbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbrgActionPerformed(evt);
            }
        });
        jMenu2.add(mbrg);

        mksr.setText("Kasir");
        mksr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mksrActionPerformed(evt);
            }
        });
        jMenu2.add(mksr);

        mplgn.setText("Pelanggan");
        mplgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mplgnActionPerformed(evt);
            }
        });
        jMenu2.add(mplgn);

        jMenuBar1.add(jMenu2);

        mnota.setText("Transaksi");
        mnota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnotaActionPerformed(evt);
            }
        });

        nota.setText("Nota");
        nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaActionPerformed(evt);
            }
        });
        mnota.add(nota);

        jMenuBar1.add(mnota);

        jMenu3.setText("Laporan");

        lapPeng.setText("Laporan Pengguna");
        lapPeng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapPengActionPerformed(evt);
            }
        });
        jMenu3.add(lapPeng);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbrgActionPerformed
        // TODO add your handling code here:
        new barang().setVisible(true);
    }//GEN-LAST:event_mbrgActionPerformed

    private void mksrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mksrActionPerformed
        // TODO add your handling code here:
        new kasir().setVisible(true);
    }//GEN-LAST:event_mksrActionPerformed

    private void mplgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mplgnActionPerformed
        // TODO add your handling code here:
        new pelanggan().setVisible(true);
    }//GEN-LAST:event_mplgnActionPerformed

    private void mnotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnotaActionPerformed
        new nota().setVisible(true);
    }//GEN-LAST:event_mnotaActionPerformed

    private void notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaActionPerformed
        // TODO add your handling code here:
        new nota().setVisible(true);
    }//GEN-LAST:event_notaActionPerformed

    private void lapPengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapPengActionPerformed
        try{
            String path="./src/report/reportPengguna.jasper";
            HashMap paramater = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, paramater, conn);
            JasperViewer.viewReport(print, false);
        }catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane,"DOkumen Tidak ada "+ex);
        }
    }//GEN-LAST:event_lapPengActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem lapPeng;
    private javax.swing.JMenuItem mbrg;
    private javax.swing.JMenuItem mksr;
    private javax.swing.JMenu mnota;
    private javax.swing.JMenuItem mplgn;
    private javax.swing.JMenuItem nota;
    // End of variables declaration//GEN-END:variables
}
